QuizletWebMvc/ViewModels/User/ChangeGmailViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace QuizletWebMvc.ViewModels.User
{
    public class ChangeGmailViewModel
    {
        [Display(Name = "Email address")]
        [Required(ErrorMessage = "Email address is required")]
        [EmailAddress(ErrorMessage = "Invalid email address")]
        public string Gmail { get; set; }


        public string OldGmail { get; set; }

        public string GmailCode { get; set; }
        public string RightGmailCode { get; set; }
    }
}

QuizletWebMvc/ViewModels/User/ChangePasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace QuizletWebMvc.ViewModels.User
{
    public class ChangePasswordViewModel
    {
        public int UserId { get; set; }
        [Required(ErrorMessage = "Please enter your current password.")]
        [DataType(DataType.Password)]
        public string OldPassword { get; set; }

        [Required(ErrorMessage = "Please enter a new password.")]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 3)]
        [DataType(DataType.Password)]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
    public class ChangeGmailViewModel2
    {
        public int UserId { get; set; }
        public string GmailAddress { get; set; }
    }
}

QuizletWebMvc/Controllers/ClassController.cs
using Microsoft.AspNetCore.Mvc;
using QuizletWebMvc.Services.Achivement;
using QuizletWebMvc.Services.Class;
using QuizletWebMvc.Services.Terminology;
using QuizletWebMvc.Services.Token;
using QuizletWebMvc.ViewModels.Achivement;
using QuizletWebMvc.ViewModels.Class;
using QuizletWebMvc.ViewModels.Terminology;
using System.Security.Claims;

namespace QuizletWebMvc.Controllers
{
    public class ClassController : Controller
    {
        private readonly IClassService classService;
        private readonly ITerminologyService terminologyService;
        private readonly IAchivement achivement;
        private readonly ITokenService tokenService;
        public ClassController(IClassService classService,ITerminologyService terminologyService,
                                IAchivement achivement,ITokenService tokenService)
        {
            this.terminologyService = terminologyService;
            this.classService = classService;
            this.achivement = achivement;
            this.tokenService = tokenService;
        }
        private bool CheckCurrentToken()
        {
            string token = Request.Cookies["AuthToken"];
            if (token == null) { return false; }
            ClaimsPrincipal principal = tokenService.ValidateToken(token);
            return principal != null;
        }
        public async Task<IActionResult> YourOwnClass()
        {
            if (!CheckCurrentToken())
            {
                TempData["Error"] = "Error. Please dont intrude to other personality";
                return RedirectToAction("Index", "Login");
            }
            ListClassViewModel listClassViewModel = new ListClassViewModel();
            if (int.TryParse(HttpContext.Session.GetString("UserId"), out int userId))
            {
                var classes = await classService.GetClassesByUser(userId);
                listClassViewModel.Classes = classes;
            }
            return View(listClassViewModel);
        }

        public IActionResult CreateYourOwnClass()
        {
            if (!CheckCurrentToken())
            {
                TempData["Error"] = "Error. Please dont intrude to other personality";
                return RedirectToAction("Index", "Login");
            }
            ClassViewModel cla = new ClassViewModel();
            if (int.TryParse(HttpContext.Session.GetString("UserId"), out int userId))
            {
                cla.UserId = userId;
            }
            return View(cla);
        }
        public async Task<IActionResult> HandleCreateClass(ClassViewModel classModel)
        {
            if (!CheckCurrentToken())
            {
                TempData["Error"] = "Error. Please dont intrude to other personality";
                return RedirectToAction("Index", "Login");
            }
            ModelState.Remove("LearningModule");
            if (!ModelState.IsValid)
            {
                return View("CreateYourOwnClass", classModel);
            }
            var canCreate = await classService.CreateClass(classModel);
            if (!canCreate)
            {
                TempData["Error"] = "Duplicate class name. Please fix it!!";
                return View("CreateYourOwnClass", classModel);
            }

            TempData["Success"] = "Create a class successfully";
            return RedirectToAction("YourOwnClass");
        }
        public async Task<IActionResult> EditYourOwnClass(int classId)
        {
            if (!CheckCurrentToken())
            {
                TempData["Error"] = "Error. Please dont intrude to other personality";
                return RedirectToAction("Index", "Login");
            }
            ClassViewModel cla = await classService.GetClass(classId);
            return View(cla);
        }
        public async Task<IActionResult> HandleEditYourOwnClass(ClassViewModel cla)
        {
            if (!CheckCurrentToken())
            {
                TempData["Error"] = "Error. Please dont intrude to other personality";
                return RedirectToAction("Index", "Login");
            }
            //ModelState.Remove("LearningModule");
            if (!ModelState.IsValid) return View("EditYourOwnClass", cla);
            var canUpdate = await classService.UpdateClass(cla);
            if (!canUpdate)
            {
                TempData["Error"] = "Duplicate class name. Please fix it!!";
                return View("EditYourOwnClass", cla);
            }
            TempData["Success"] = "Update class sucessfully";
            return RedirectToAction("YourOwnClass");
        }
        public async Task<IActionResult> DeleteClass(int classId)
        {
            if (!CheckCurrentToken())
            {
                TempData["Error"] = "Error. Please dont intrude to other personality";
                return RedirectToAction("Index", "Login");
            }
            var canDelete = await classService.DeleteClass(classId);

            if (!canDelete)
            {
                TempData["Error"] = "Delete this class failed because it contains links to other datas";
            }
            else
            {
                TempData["Success"] = "Delete a class sucessfully";
            }

            return RedirectToAction("YourOwnClass");
        }
        public async Task<IActionResult> ShowDetailOwnClassLearningModule(int classId)
        {
            if (!CheckCurrentToken())
            {
                TempData["Error"] = "Error. Please dont intrude to other personality";
                return RedirectToAction("Index", "Login");
            }
            HttpContext.Session.SetString("CurrentClassId",classId.ToString());
            List<ClassLearningModuleViewModel> models = await classService.GetDetailLearningModuleClass(classId);
            ClassViewModel cla = await classService.GetClass(classId);
            ListClassLearningModuleViewModel listModels = new ListClassLearningModuleViewModel();
            listModels.LearningModules = models;
            listModels.Copy(cla);
            listModels.ClassId = classId;
            return View("DetailOwnClass", listModels);

        }
        public async Task<IActionResult> TitleSelection(int classId)
        {
            if (!CheckCurrentToken())
            {
                TempData["Error"] = "Error. Please dont intrude to other personality";
                return RedirectToAction("Index", "Login");
            }
            ListChoiceTitle listChoiceTitle = new ListChoiceTitle();
            if (int.TryParse(HttpContext.Session.GetString("UserId"), out int userId))
            {
                listChoiceTitle.TitleChoiceViewModels = await classService.GetTitleDatas(userId);
                listChoiceTitle.ClassId = classId;
            }
            return View(listChoiceTitle);
        }
        public async Task<IActionResult> LearningModuleSelection(int titleId)
        {
            if (!CheckCurrentToken())
            {
                TempData["Error"] = "Error. Please dont intrude to other personality";
                return RedirectToAction("Index", "Login");
            }
            ViewModels.Class.ListLearningModuleViewModel listLearningModule = new ViewModels.Class.ListLearningModuleViewModel();
            if (int.TryParse(HttpContext.Session.GetString("CurrentClassId"), out int classId))
            {
                listLearningModule.Modules = await classService.GetModuleDatas(classId,titleId);
            }
            listLearningModule.TitleId = titleId;
            return View(listLearningModule);
        }
        public async Task<IActionResult> AddModuleToClass(int learningModuleId,int titleId)
        {
            if (!CheckCurrentToken())
            {
                TempData["Error"] = "Error. Please dont intrude to other personality";
                return RedirectToAction("Index", "Login");
            }
            if (int.TryParse(HttpContext.Session.GetString("CurrentClassId"), out int classId))
            {
                LearningModuleDetail detail = new LearningModuleDetail();
                detail.ClassId = classId;
                detail.LearningModuleId = learningModuleId;
                
                var check = await classService.AddModuleToClass(detail);
                if(!check)
                {
                    TempData["Error"] = "Cannot add module to class. Server error";
                   
                }
                else
                {
                    TempData["Success"] = "Add module to class successfully";
                }
            }
            
            return RedirectToAction("LearningModuleSelection", new {titleId = titleId});
        }
        public async Task<IActionResult> DeleteModuleFromClass(int learningModuleId, int titleId,string typePage = "")
        {
            if (!CheckCurrentToken())
            {
                TempData["Error"] = "Error. Please dont intrude to other personality";
                return RedirectToAction("Index", "Login");
            }
            if (int.TryParse(HttpContext.Session.GetString("CurrentClassId"), out int classId))
            {
                var check = await classService.DeleteModuleDetail(classId,learningModuleId);
                if (!check)
                {
                    TempData["Error"] = "Cannot delete module from class. Server error";

                }
                else
                {
                    TempData["Success"] = "Delete module from class successfully";
                }
            }
            if(typePage=="choose")
            {
                return RedirectToAction("LearningModuleSelection", new { titleId = titleId });
            }
            else
            {
                return RedirectToAction("ShowDetailOwnClassLearningModule", new { classId = classId });
            }
            
        }

        public async Task<IActionResult> ShowDetailOwnClassParticipant(int classId)
        {

QuizletWebMvc/Views/Home/ChangeGmail.cshtml
@using QuizletWebMvc.ViewModels.User;
@model ChangeGmailViewModel;

@{
    ViewData["Title"] = "Change gmail";
    Layout = null;
}
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@{
    string typeUser = HttpContextAccessor.HttpContext.Session.GetString("TypeUser");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <partial name="HeaderHome" />

</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_sidebar.html -->
        @if (typeUser == "Admin")
        {
            <partial name="Admin_Navigation" />
        }
        else
        {
            <partial name="_Navigation" />
        }

        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_navbar.html -->
            @if (typeUser == "Admin")
            {
                <partial name="AdminTopNavbar" />
            }
            else
            {
                <partial name="TopNavbar" />
            }
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper" id="contentContainer">
                    <div class="row">
                        <div class="col-lg-12 grid-margin stretch-card">
                            <div class="card">
                                <div class="card-body">
                                    <h2>Change Gmail</h2>
                                    @using (Html.BeginForm("ChangeGmail", "Home", FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Gmail)
                                            @Html.TextBoxFor(model => model.Gmail, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.Gmail, "", new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group" style="display: none;">
                                            @Html.LabelFor(model => model.OldGmail)
                                            @Html.TextBoxFor(model => model.OldGmail, new { @class = "form-control" })
                                        </div>

                                        <!-- Add other form fields as needed -->

                                        <button type="submit" class="btn btn-primary">Update</button>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="loading" style="display: none;">Loading...</div>
                <!-- content-wrapper ends -->
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <partial name="FooterHome" />
</body>
</html>

QuizletWebMvc/Views/Home/ChangePassword.cshtml
@using QuizletWebMvc.ViewModels.User;
@model ChangePasswordViewModel;

@{
    ViewData["Title"] = "Change password";
    Layout = null;
}
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@{
    string typeUser = HttpContextAccessor.HttpContext.Session.GetString("TypeUser");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <partial name="HeaderHome" />

</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_sidebar.html -->
        @if(typeUser=="Admin")
        {
            <partial name="Admin_Navigation" />
        }
        else
        {
            <partial name="_Navigation" />
        }
        
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_navbar.html -->
            @if(typeUser=="Admin")
            {
                <partial name="AdminTopNavbar" />
            }
            else
            {
                <partial name="TopNavbar" />
            }
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper" id="contentContainer">
                    <div class="row">
                        <div class="col-lg-12 grid-margin stretch-card">
                            <div class="card">
                                <div class="card-body">
                                    <h2>Change Password</h2>

                                    @using (Html.BeginForm("ChangePassword", "Home", FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()

                                        <div class="form-group">
                                            @Html.LabelFor(m => m.OldPassword, new { @class = "control-label" })
                                            @Html.PasswordFor(m => m.OldPassword, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(m => m.OldPassword, "", new { @class = "text-danger" })
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(m => m.NewPassword, new { @class = "control-label" })
                                            @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(m => m.NewPassword, "", new { @class = "text-danger" })
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(m => m.ConfirmPassword, new { @class = "control-label" })
                                            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "text-danger" })
                                        </div>

                                        <button type="submit" class="btn btn-primary">Change</button>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="loading" style="display: none;">Loading...</div>
                <!-- content-wrapper ends -->
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <partial name="FooterHome" />
</body>
</html>

QuizletWebMvc/Views/Home/HomeGmailChecking.cshtml
@using QuizletWebMvc.ViewModels.User;
@model ChangeGmailViewModel;

@{
    ViewData["Title"] = "Home gmail checking";
    Layout = null;
}
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@{
    string typeUser = HttpContextAccessor.HttpContext.Session.GetString("TypeUser");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <partial name="HeaderHome" />

</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_sidebar.html -->
        @if (typeUser == "Admin")
        {
            <partial name="Admin_Navigation" />
        }
        else
        {
            <partial name="_Navigation" />
        }

        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_navbar.html -->
            @if (typeUser == "Admin")
            {
                <partial name="AdminTopNavbar" />
            }
            else
            {
                <partial name="TopNavbar" />
            }
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper" id="contentContainer">
                    <div class="row">
                        <div class="col-lg-12 grid-margin stretch-card">
                            <div class="card">
                                <div class="card-body">
                                    <h2>We just send you a 6 digits code to email: @Model.OldGmail</h2>
                                    <h2>Please enter this code.</h2>
                                    @using (Html.BeginForm("GmailChecking", "Home", FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.GmailCode)
                                            @Html.TextBoxFor(model => model.GmailCode, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.GmailCode, "", new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group" style="display: none;">
                                            @Html.LabelFor(model => model.RightGmailCode)
                                            @Html.TextBoxFor(model => model.RightGmailCode, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.RightGmailCode, "", new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group" style="display: none;">
                                            @Html.LabelFor(model => model.Gmail)
                                            @Html.TextBoxFor(model => model.Gmail, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.Gmail, "", new { @class = "text-danger" })
                                        </div>
                                        <div class="form-group" style="display: none;">
                                            @Html.LabelFor(model => model.OldGmail)
                                            @Html.TextBoxFor(model => model.OldGmail, new { @class = "form-control" })
                                        </div>

                                        <!-- Add other form fields as needed -->

                                        <button type="submit" class="btn btn-primary">Send</button>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="loading" style="display: none;">Loading...</div>
                <!-- content-wrapper ends -->
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <partial name="FooterHome" />
</body>
</html>

QuizletWebMvc/Views/Home/Index.cshtml
@using QuizletWebMvc.ViewModels.Achivement;
@{
    ViewData["Title"] = "Home Page";
    Layout = null;
}
@model UserAchivement;
<!DOCTYPE html>
<html lang="en">
<head>
    <partial name="HeaderHome" />
    <style>
        .small-text {
            font-size: 10px;
        }

        .card-small-body {
            background-color: #6fdcdc;
        }

        .my-card:hover {
            transform: scale(1.05); /* You can adjust the scaling factor as desired */
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.8); /* Add a box shadow for elevation */
            border: 1px solid transparent; /* Initially, the border is transparent */
            background-color: transparent; /* Initially, the background is transparent */
        }

        .card img {
            width: 100px; /* Adjust the width of the image as needed */
            height: auto; /* Maintain the aspect ratio */
            margin-bottom: 10px;
        }
    </style>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        window.onload = function () {
            // Get a reference to the canvas element.
            var ctx = document.getElementById('barChart').getContext('2d');
            var modelData = @Html.Raw(Json.Serialize(Model));
            var levelNames = [];
            var numberTerms = [];
            for (var i = 0; i < modelData.levelTerms.length; i++) {
                var level = modelData.levelTerms[i];
                levelNames.push(level.levelName);
                numberTerms.push(parseInt(level.numberTermsInLevel, 10));
            }
           
            // Define your data for the chart.
            var data = {
                labels: levelNames,
                datasets: [{
                    label: 'Terminology',
                    data: numberTerms,
                    backgroundColor: 'rgba(75, 192, 192, 0.2)', // Bar fill color
                    borderColor: 'rgba(75, 192, 192, 1)', // Bar border color
                    borderWidth: 1, // Bar border width
                    barThickness: 50
                }]
            };

            // Create the bar chart.
            var barChart = new Chart(ctx, {
                type: 'bar', // Chart type (bar chart)
                data: data,
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    },

                }
            });
        };
    </script>
    <script>
        var pageNumber = 0;
        var isLoading = false;
        var noMoreItems = false;

        function loadMoreContent() {
            if (!isLoading && !noMoreItems) {
                if (pageNumber == 0) { 
                    pageNumber++;
                    return;
                }
                isLoading = true;
                $("#loading").show();
                $.ajax({
                    url: '@Url.Action("LoadMoreAchivement", "Home")',
                    type: 'GET',
                    data: { pageNumber: pageNumber },
                    success: function (data) {
                        if (data) {
                            $("#contentContainer").append(data);
                            pageNumber++;
                            isLoading = false;
                            $("#loading").hide();
                        } else {
                            noMoreItems = true;
                            $("#loading").hide();
                        }
                    },
                    error: function (xhr, status, error) {
                        alert("AJAX request failed with status: " + status + " and error: " + error);
                        isLoading = false;
                        $("#loading").hide();
                    }
                });
            }
        }

        $(window).on('scroll', function () {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 10) {
                loadMoreContent();
            }
        });

        // Load initial content
        loadMoreContent();
    </script>
    
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .calendar {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            grid-gap: 5px;
        }

        .day {
            border: 1px solid #ccc;
            padding: 10px;
            text-align: center;
            position: relative;
            cursor: pointer;
        }

        .event-marker {
            background-color: #3498db;
            opacity: 0.6;
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            pointer-events: none;
        }

        .month-year {
            text-align: center;
            margin-bottom: 10px;
        }
    </style>
    
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_sidebar.html -->
        <partial name="_Navigation"/>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_navbar.html -->
            <partial name="TopNavbar" />
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper" id="contentContainer">
                    <div class="row">
                        <div class="col-lg-12 grid-margin stretch-card">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="card-title">Level terms</h4>
                                    <canvas id="barChart" width="400" height="150"></canvas>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="loading" style="display: none;">Loading...</div>
                <!-- content-wrapper ends -->
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <partial name="FooterHome" />
</body>
</html>

QuizletWebMvc/Views/Home/_MessageListPartial.cshtml
@using QuizletWebMvc.ViewModels.Class;
@{
    var messages = ViewBag.Messages as List<MessageClassRegistration>;
}

@if (messages != null && messages.Any())
{
    foreach (var message in messages)
    {
        <a href="@Url.Action("ShowDetailOwnClassPendingParticipant", "Class",new{classId=message.ClassId})" class="dropdown-item preview-item">
            <div class="preview-thumbnail">
                @if(message.ImageUrl==null)
                {
                    <img src="~/assets/images/faces/face15.jpg" alt="image" class="rounded-circle profile-pic">
                }
                else
                {
                    <img src=@message.ImageUrl alt="image" class="rounded-circle profile-pic">
                }
               
            </div>
            <div class="preview-item-content">
                <p class="preview-subject ellipsis mb-1">@message.NameRegister wanna join : @message.ClassName</p>
                <p class="text-muted mb-0">@message.DateRegister</p>
            </div>
        </a>
        <div class="dropdown-divider"></div>
    }

    <p class="p-3 mb-0 text-center">@messages.Count new messages</p>
}
else
{
    <p class="p-3 mb-0 text-center">No messages available</p>
}